version: '3.0'
services:

  web:
    build: .
    ports:
      - "8140:8000"

  train:
    build:
      context: .
      dockerfile: train.dockerfile
    volumes:
      - ./app:/app
      - ./input:/input
      - ./nltk/data:/nltk/data
      - ./output:/output
